### ISSUE TITLE
No such file or directory: 'tensorflow-models/syntaxnet/bazel-bin/syntaxnet/parser_eval'

### ISSUE THREAD

**Issue by bekerov** [askplatypus/syntaxnet-api#3]
Tryed on Ubuntu 16 EN language but have error. I checked path but bazel-bin doesnt exist.
```
b'i saw the man with glasses'
en
[2017-01-19 15:41:05,804] ERROR in app: Exception on /v1/parsey-universal-full [POST]
Traceback (most recent call last):
  File "/home/bekerov/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bekerov/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bekerov/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bekerov/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bekerov/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bekerov/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_server.py", line 44, in _parsey_universal_full_handler
    conllu = parsey.parsey_universal_full_conllu(text, language_code)
  File "/home/bekerov/syntaxnet-api/parsey.py", line 168, in parsey_universal_full_conllu
    result = _loaded_models_futures[language_code].result().full_parse_conllu(text)
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bekerov/syntaxnet-api/parsey.py", line 93, in __init__
    ], stdin=PIPE, stdout=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'tensorflow-models/syntaxnet/bazel-bin/syntaxnet/parser_eval'
```

**Comment by Tpt** [comment]
Have you run sh install-syntaxnet-debian.sh ?

**Comment by bekerov** [comment]
sure.
used your instruction

**Comment by Tpt** [comment]
I've tried to do a clean install on Ubuntu 16.04. Not manage to reproduce your issue. it's probably caused by an error during SyntaxNet compilation. Did you have any error message while running "sh install-syntaxnet-debian.sh" ?
